
log:
  level: "debug" # Log level (debug, info, warn, error, dpanic, panic, fatal)
  outputPath: "logs/server.log" # Log output file path (if empty, logs will only be printed to console)
  maxSize: 100 # Maximum size in MB of the log file before it gets rotated
  maxBackups: 7 # Maximum number of old log files to retain
  maxAge: 30 # Maximum number of days to retain old log files
  compress: true # Whether to compress old log files
  enableConsole: true # Whether to also log to console

zdan:
  openBaseURL: http://10.10.16.146:8080
  apiServerKey: "sk-AnxkuFzRpmZq87Uydk6RCM1fbqQkv1WE" # API网关访问密钥
  apiServiceId: "EB34212D8AB69D0D2F2B7085760ED8BDB87C8E5C" # 本服务ID
