server:
  port: 8080 # Server listening port
  host: "0.0.0.0" # Server listening address

log:
  level: "debug" # Log level (debug, info, warn, error, dpanic, panic, fatal)
  outputPath: "logs/server.log" # Log output file path (if empty, logs will only be printed to console)
  maxSize: 100 # Maximum size in MB of the log file before it gets rotated
  maxBackups: 7 # Maximum number of old log files to retain
  maxAge: 30 # Maximum number of days to retain old log files
  compress: true # Whether to compress old log files
  enableConsole: true # Whether to also log to console

zdan:
  zdanHost: "192.168.3.181" # 分布式节点访问地址
  zdanPort: 10015 # 分布式节点访问端口
  cloudDmappId: "9ADDD75FAA063AF78250444A19CEDBFE55607985" # 零极云管理系统ID
  cloudDmappKey: "CeuOmcVx7HvtKEAKafDdBDM+sITa2POSmOpM2XWbJCI=" # 零极云管理系统密钥
  cloudUserId: "Ztwv2hV14r2smkZ3WXYQFFj6sY6gjguuEZ" # 零极云管理员工ID
  userDmappId: "2A5D8B89CB49D2AD0325F3E419FEC31F2D218EA2" # 零极云开放平台ID
  userDmappKey: "H5ahKWk20AAjEyma3b33Ir45z4AAed5dRZt6s2LrdCg=" # 零极云开放平台密钥

database:
  host: "192.168.3.181" # Database host
  port: 5432 # Database port
  user: "postgres" # Database user
  password: "123456" # Database password
  dbname: "openai_db" # Database name
  sslmode: "prefer" # Database SSL mode (disable, allow, prefer, require, verify-ca, verify-full)