server:
  port: 8080 # Server listening port
  host: "0.0.0.0" # Server listening address

zdan:
  cloudDmappId: "9ADDD75FAA063AF78250444A19CEDBFE55607985" # ZDAN cloud dmapp
  cloudDmappKey: "CeuOmcVx7HvtKEAKafDdBDM+sITa2POSmOpM2XWbJCI=" # ZDAN cloud app key
  userDmappId: "9ADDD75FAA063AF78250444A19CEDBFE55607985" # ZDAN user dmapp
  userDmappKey: "CeuOmcVx7HvtKEAKafDdBDM+sITa2POSmOpM2XWbJCI=" # ZDAN user app key

